### ISSUE TITLE
ver. 5.0.7 not recognising Xe

### ISSUE THREAD

**Issue by rdmpz** [zorkzou/Molden2AIM#14]
Dear zorkzou,

I am having a problem where molden2aim does not recognize Xe in my molden file. The molden file begins like this:

      [Molden Format]
      [Title]
      acxe12                                                                               
      [Atoms] AU
      ac    1   89 -.12029448356470E-01 0.30476999032274E+00 -.21259190877886E+00
      xe    2   54 -.79773992204133E+00 0.65596717351131E+01 0.35530604684190E+01
      xe    3   54 0.62053052742417E+00 0.65427510363090E+01 -.40340871887865E+01
      xe    4   54 -.62002749265462E+01 0.40815761188483E+01 -.13823377528108E+01
      xe    5   54 0.60838186436916E+01 0.42457935641787E+01 0.92200528872291E+00
      xe    6   54 0.61757842726747E+01 -.34718275046404E+01 0.95705647748682E+00
      xe    7   54 -.64490885320323E+00 -.59329760522434E+01 0.36083728037720E+01
      xe    8   54 -.61083842161548E+01 -.36361679107900E+01 -.13474693549736E+01
      xe    9   54 0.77336630488126E+00 -.59499085311553E+01 -.39787490910088E+01
      xe   10   54 0.26378963237344E+01 0.36899022850519E+00 0.66495093007157E+01
      xe   11   54 -.49479367044666E+01 0.26806036547439E+00 0.52150117063170E+01
      xe   12   54 -.26623212659002E+01 0.24077778289548E+00 -.70747458334377E+01
      xe   13   54 0.49237435470384E+01 0.34153410327845E+00 -.56403781306256E+01

and molden2aim returns:

     This MOLDEN file was generated by TURBOMOLE

     SUMMARY

     Number of atoms:                                 1
     Maximum angular momentum:                        4
     Number of primitive GTF shells:                 48
     Number of contracted GTF shells:                31
     Number of primitive Cartesian functions:       238
     Number of contracted Cartesian functions:      152
     Number of primitive spherical functions:       186
     Number of contracted spherical functions:      117

      *** Wrong! nbasmo=  680, NCGTO=  152

There should be 13 atoms total, 12 of which are Xe. I have tried changing Xe to Ar and Kr in my molden file and molden2aim reads the number of atoms correctly. I have also used molden2aim many times with Turbomole generated molden files without issue so I think it is Xe-specific. 

Best,
rdmpz

**Comment by zorkzou** [comment]
Dear rdmpz,

Thank you for reporting the bug, which has been fixed in the latest version.

Best regards,
zorkzou

**Comment by rdmpz** [comment]
Dear zorkzou,

Thank you for the fast update, it works now!

Best,
rdmpz
