### ISSUE TITLE
About the ghost atom

### ISSUE THREAD

**Issue by mhyeok1** [zorkzou/Molden2AIM#15]
Dear Developer,

I am truly grateful for the wonderful program you have developed.
As many programs make bad molden files as you know, This program helps me a lot.

I write to you with a query regarding the ghost atom feature.
It appears that ghost atom is not currently supported in the molden2aim program.
I was wondering if there are any plans to include this feature in a future update.

Kindly looking forward to your response.

Best Regards,
Minhyeok Lee

**Comment by zorkzou** [comment]
Dear Minhyeok Lee,

It is not difficult to support ghost atom in terms of technology.
Please let me know the quantum chemistry program you are using, and
I'll have a test this summer.

Best regards,
Wenli

**Comment by mhyeok1** [comment]
Dear Wenli,

Thank you for your kind response!
I am utilizing pyscf for my calculations.
I sincerely appreciate your support.

Best Regards,
Minhyeok Lee

**Comment by mhyeok1** [comment]
Thank you for your support!
It works as I expected!
