### ISSUE TITLE
Got "Normalization check failed." when generate a *.wfn from a molden file of ORCA 

### ISSUE THREAD

**Issue by NKUCodingCat** [zorkzou/Molden2AIM#5]
As title said, when I use Molden2AIM to format the molden file from ORCA, it generate a *wfn file and asked if I want to check the WFN file. And I got 
```
Reading basis functions...
Computing the overlap matrix...
Computing the integrated number of electrons...

Sum of MO Occupancies                       =      80.0000000000
Analytically integrated number of electrons =      71.2593433275 
Difference                                  =       8.7406566725
Difference per atom                         =       0.5827104448

 ### Warning! Normalization check failed.
```

I tried several molden file and ALL of them leads to same result. Does it mean that something goes wrong when I run ORCA? I cannot find any error from ORCA output

[CAA97BD3.zip](https://github.com/zorkzou/Molden2AIM/files/1851040/CAA97BD3.zip)
[CBABAC20.zip](https://github.com/zorkzou/Molden2AIM/files/1851041/CBABAC20.zip)

Here are some sample of the molden file and ORCA input/output

**Comment by zorkzou** [comment]
Dear Dr. JingTao,

For the molden file generated by orca, you have to insert a special line
with the text "[Program] Orca" into it.
Alternatively, you may set up "program=1" in m2a.ini.

Best regards,
Wenli

**Comment by NKUCodingCat** [comment]
Solved
