### ISSUE TITLE
Counterpoise Corrected WF (remove nulceii)

### ISSUE THREAD

**Issue by goofus** [zorkzou/Molden2AIM#7]
Hi
I would like to process a molden file generated in ORCA using more basis functions. The problem is that the molden file contains the nuclei. It would be useful in that case to declare them as [core], but molden2aim doesn't let me do it:

`## Error in core data: ZA <= NCore!`

**Comment by zorkzou** [comment]
NCore is not the total number of core electrons. Can you show me your
molden file, or just the [Atoms] and [Core] (or [Pseudo]) sections?

**Comment by goofus** [comment]
Thank you for your answer, here is the molden file for a very simple example.
The molden file was created using orca_2mkl h2o -molden

[h2o.inp.txt](https://github.com/zorkzou/Molden2AIM/files/3478418/h2o.inp.txt)
[h2o.molden.input.txt](https://github.com/zorkzou/Molden2AIM/files/3478422/h2o.molden.input.txt)

**Comment by zorkzou** [comment]
It seems that they are orca data files, not in molden. def2-SVP does
not contain core electrons for H and O, so [core] is not needed.

**Comment by goofus** [comment]
Please try to open the molden file with molden2aim (h2o.molden.input.txt) and you will see the problem. In that case I calculated E(H2) in the basis of H2O. Molden2aim seems to compare the occupation number with the basis functions and doesn't open the molden input file.

**Comment by zorkzou** [comment]
According to the steep basis functions in [GTO], there should be no
core electrons replaced by ECP. In the [MO] block there is only one
occupied orbital, so this is a water molecule with +8 charges. If this
is true, you may just ignore the question about ECP, and then choose
"ionic system". Otherwise you may check your orca calculations.

**Comment by goofus** [comment]
It does not have a charge and it is not a water molecule. It is H H with the O nuclear charge set to zero. The total energy is -1.049784466360 hartree, this and also the orbital energy would be much lower otherwise.
It is just two hydrogen atoms in the basis of H2O. The basis functions of oxygen are centered at the position where the oxygen would be in H2O. Just like you do if you want to calculate the counterpoise correction.

**Comment by zorkzou** [comment]
In your case it may be looked on as a charged system (H2O^8+). In
general a gohst atom does not affect the results of AIM and NBO.
However, if you are not sure about this, you may change the oxygen
atom to another one (for example, He or Li), and see whether the AIM
or NBO results are the same.
