### ISSUE TITLE
molden file from turbomole

### ISSUE THREAD

**Issue by angelikac86** [zorkzou/Molden2AIM#8]
I have an open shell system (Unrestricted-DFT) and I use TURBOMOLE for the calculations and to obtain the .molden file. When I use M2A to generate the .47 file, and then run it for an NBO7 calculation, the NBO7 output indicates that I have a restricted open shell system. Therefore, instead of showing all the molecular orbitals with an occupancy of 1, it shows them with an occupancy of 2 (except for the singly occupied according to restricted open shell). Is there a keyword that I can use in the .molden file that I can specify that I'm using unrestricted open-shell so that I can generate the correct .47 file?
molden file example:
![Uploading molden.png…]()

example of NBO7 output, occupancy: 
![occupancy](https://user-images.githubusercontent.com/66896733/84585633-c322d500-ae09-11ea-9750-da9d8ce062cd.png)

**Comment by zorkzou** [comment]
Hi! If you are using the 5.0 version, you may set carsph=1 in m2a.ini
(which will be generated on the first run), then the alpha and beta density
matrices will be printed separately.

**Comment by angelikac86** [comment]
Hi! I tried that but it didn’t really change anything.

**Comment by zorkzou** [comment]
Some versions of NBO require #MO(alpha) = #MO(beta) = #basis, which is
also checked by m2a.
Would you please send me your molden file?

**Comment by angelikac86** [comment]
Hi, I have attach a molden file for simple case (just neptunyl Np(V)O2) of an unrestricted open shell case. If you can make it work for this one, then it will probably work for my larger systems. Thank you so much, I really appreciate your help very much.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by zorkzou** [comment]
Hi, I didn't receive you molden file. Please also send it to
zouwl@nwu.edu.cn. Thank you!

**Comment by zorkzou** [comment]
Hi Angelika,

I just found there was a typo in my first reply. nbopro=1 in m2a.ini
may solve your problem.

Best regards,
Wenli

**Comment by angelikac86** [comment]
Thank you Wenli, it worked finally!! Thank you so much!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
